[project]
name = "comfyui-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pixeldj", email = "superdj@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "websockets>=17.1",
]

[project.scripts]
comfyui-client = "comfyui_client:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
